name: qapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 3.10.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  responsive_builder: ^0.4.3
  http: ^0.13.5
  freezed: ^2.3.2
  provider: ^6.0.5
  change_app_package_name: ^1.1.0
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.1.0
  scroll_to_index: ^3.0.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  material_floating_search_bar: ^0.3.7
  url_launcher: ^6.1.7
  shimmer: ^2.0.0
  carousel_slider: ^4.2.1
  lottie: ^2.1.0
  equatable: ^2.0.5
  sliding_up_panel: ^2.0.0+1
  image_picker: ^0.8.6
  mask_text_input_formatter: ^2.4.0
  fluttertoast: ^8.1.2
  collection: ^1.16.0
  app_settings: ^4.2.0
  cached_network_image: ^3.2.3
  lazy_load_scrollview: ^1.3.0
  device_info: ^2.0.3
  badges: ^2.0.3
  package_info: ^2.0.2
  connectivity_plus: ^3.0.2
  auto_size_text: ^3.0.0
  page_view_indicators: ^2.0.0
  glassmorphism: ^3.0.0
  dio_cookie_manager: ^2.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  build_runner: ^2.3.3
  cookie_jar: ^3.0.1
  syncfusion_flutter_calendar: ^20.4.42
  shared_preferences: ^2.0.15
  timer_builder: ^2.0.0
  fimber: ^0.6.6
  flutter_switch: ^0.3.2
  landscape_textfield: ^0.0.2
  popover: ^0.2.8
  syncfusion_flutter_charts: ^20.4.42
  fl_chart: ^0.55.2
  flutter_bootstrap: ^2.0.0
  path_provider: ^2.0.11
  device_preview: ^1.1.0
  dropdown_search: ^5.0.5
  camera: ^0.10.1
  path: ^1.8.2
  status_change: ^2.0.0
  otp_text_field: ^1.1.3
  dio: ^4.0.6
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^2.1.0
  multi_select_flutter: ^4.1.3
  multiselect: ^0.1.0
  sqflite: ^2.2.7
  pie_chart: ^5.3.2
  ota_update: ^5.1.0
  gallery_saver: ^2.0.3
  flutter_image_compress: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/splash/
    - assets/svg/
    - assets/login/
    - assets/logo.png
    - assets/dashboard/
    
fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-ExtraBold.ttf
        - asset: fonts/Inter-ExtraLight.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf